### ISSUE TITLE
"Live Looping"

### ISSUE THREAD

**Issue by deadpahn** [asiekierka/nitrotracker#10]
Another great feature to have would be the ability to "live loop". What I mean by that is queuing up the next pattern to be played. Right now I've been doing it by ear (in loud clubs lol) and it works but ... it would be a lot more reliable if it would only jump to the next pattern when the currently played pattern is finished. A simple "LIVE LOOP" toggle button (or "queue pattern" ... name doesn't matter to me whatever make sense) that knows "only play the next "queued" pattern when the current one is finished playing". I use this for cheap remixing on the fly.

Here is a primitive mock up of the idea:
![image](https://user-images.githubusercontent.com/1032331/219981546-12bac5fb-e5c1-47c4-a7b1-06691e6a3fc1.png)

The pattern highlighted in purple would be in line to be played (when the current one stops playing). Old instant pattern jumping should still be available, hence the toggle button. Renoise implements this pretty good if you are looking for ideas on that one. 

Thanks!

**Comment by asiekierka** [comment]
I think that this behaviour should just be the default if you try to switch patterns while a song is already playing.

**Comment by asiekierka** [comment]
Or as a toggle, as per https://github.com/asiekierka/nitrotracker/issues/4

**Comment by asiekierka** [comment]
![](https://img.asie.pl/FiN1.png)

How does this look? I've used the opportunity to clean up the song/pattern tab a little bit.

**Comment by deadpahn** [comment]
### _This is incredible._

I can't even begin to tell you how much this will open to live jammers and live artist. I haven't put it through it's paces yet but so far so good. The Nav focus is a bit weird, I don't have a good solution/idea for it yet so I'll work with it. When you scroll way down in the song to find a pattern, if you aren't quick, it goes back to where the cursor is. Not a deal breaker, just awkward.

I'm so excited about this and I can't wait for the community to catch wind of it. I dunno if I'm chasing the high of going to OG chiptune parties in the 00's but I can see this catching on. Nitrotracker is a legit daw now. You can bring it around with you, load a couple of amens, and get work done on the bus etc. Gear gets stolen? Grab another DSi from ebay for $40 lol.

**Comment by asiekierka** [comment]
The scrolling behaviour should be fixed in the next release.
