### ISSUE TITLE
Support for loading flac files

### ISSUE THREAD

**Issue by exelotl** [asiekierka/nitrotracker#103]
Some sample packs come in flac rather than wav. It would be nice to be able to load them without having to convert them on my PC first!

**Comment by deadpahn** [comment]
This would break compatibility with other trackers (Fasttracker 2) wouldn't it? Also the overhead this adds to the already taxed DS hardware seems like it would be an issue but I'm not sure about that (just a guess).

I wrote a script using [SOX](https://linux.die.net/man/1/sox) to convert all of my DS samples, works like a dream. IMO you don't even want to use stereo 16bit wav files in the first place ([the dacs on the DS won't play them correctly anyway](https://retrocomputing.stackexchange.com/questions/24952/is-sound-generation-on-the-nintendo-ds-always-clipped-to-10-bits)). Think of Nitrotracker as an Akai S900 in your pocket.

**Comment by asiekierka** [comment]
Overhead isn't really the problem; sample import and conversion can take however long it wants. My concern is that adding a FLAC reading library would add a lot of overhead to the code size, and thus RAM usage.

**Comment by exelotl** [comment]
This is fair, sox gives me a headache but I guess it's no problem for me to spend a bit of time to get some batch conversion working, especially if it's best to preconvert the samples to mono anyways. Flac loading is definitely not an essential feature, I guess we can close this?
