### ISSUE TITLE
Adjustable lines per beat

### ISSUE THREAD

**Issue by exelotl** [asiekierka/nitrotracker#111]
Currently there is a dividing line in the pattern grid every 8 rows. It would be nice to have the ability to adjust this, to make it easier to work with time signatures other than 4/4.

**Comment by asiekierka** [comment]
Would this just require changing the value of `every N rows`, or are there more diverse requirements?

**Comment by exelotl** [comment]
No additional requirements, it would be a purely visual change. MilkyTracker and others seem to store the line spacing in the program settings. But if it were possible to store it as song metadata somehow that could be neat.

**Comment by asiekierka** [comment]
Solved by storing in the program settings, as suggested.
