### ISSUE TITLE
Freeze when trying to record a sample for too long

### ISSUE THREAD

**Issue by exelotl** [asiekierka/nitrotracker#112]
I opened up the recording dialog and held (A) to attempt to record a voice clip slightly over 10 seconds in length.

Upon releasing (A), I found the app had gotten stuck in the recording state and did not respond to any of my inputs, so I had to power off my console.

I booted up again and recorded a short (2 second) sample, which worked fine. I then tried to re-record my 10 second sample, this time by pressing (B) instead of holding (A), and got the same hang as before.

I haven't explored further, but can assume at this point that attempting to record a sample beyond a certain length will always cause NitrousTracker to hang.

Note: I'm running NitrousTracker off the SD card via hbmenu on a recently hacked DSi XL

**Comment by deadpahn** [comment]
Yeah. The record feature has been buggy since a two or three releases ago. The "hold" method and "press" method both got issues but the "press" method fails a lot yeah.
