### ISSUE TITLE
Map samples button UI issue

### ISSUE THREAD

**Issue by romanconstantin1** [asiekierka/nitrotracker#117]
On the standard DSi screen, the Map Samples and Set Sustain buttons are overlapping. This is a minor visual issue & doesn't seem to affect performance, but it does make switching between setting envelopes & mapping samples a little fiddly. I don't have an XL or 3DS to test with, so I'm not sure if the problem is replicated there. The attached picture is from 0.4.9, but the issue is present in 0.4.10 as well
![WhatsApp Image 2024-07-20 at 10 06 20](https://github.com/user-attachments/assets/ab09539d-c773-4def-8eaa-fcdda95c742d)

**Comment by deadpahn** [comment]
Can confirm this is happening on DSi via r4 and 3DS via r4/DS mode
