### ISSUE TITLE
some wavs get improperly filtered out in the file browser

### ISSUE THREAD

**Issue by faithanalog** [asiekierka/nitrotracker#122]
the file browser helpfully filters by file extension, but for some reason i have 3 folders worth of wav files that it filters out (despite them ending in .wav).

What I know:

1. they actually end in `.wav`, there's no funny extra chars in the file. I checked this with `ls | xxd` to check the hex of the the file names
2. They are actually audio files. When I removed the file extension filtering from the code, they played fine
3. I used to have some files with the exact same names, and they showed up in the file browser. The new ones were generated by `sox`-ing them into a format that's a bit friendlier for my tracking
4. It's lowercase `.wav` and not uppercase `.WAV`
5. Other wavs in other folders show up fine

What I don't know, yet: what the file extension filterer actually thinks the file extension is. I do know where I'd check, but I'm not sure the best way to get debug logs out of this software yet (most of my own nds homebrew so far has been printf-logging to a console on the bottom screen, so I'm not sure what you do when you have both screens in use for your software.)

**Comment by asiekierka** [comment]
> most of my own nds homebrew so far has been printf-logging to a console on the bottom screen, so I'm not sure what you do when you have both screens in use for your software.

printf-logging to a console on the *top* screen; this is what the `nitrotracker.debug.nds` variant is for, the console is overlaid on top of the normal content.

**Comment by faithanalog** [comment]
oh excellent!!

**Comment by faithanalog** [comment]
Ok I got it printing extensions, but also, everything is working now. It's possible that I just had it on "song" filter. I don't *think* that's the case, because I am pretty sure I navigated to a different folder, listed samples, nav'd back to the problem folder, didnt see any. But... if I can't reproduce it, I've got to assume it was a me problem unless I hit it again.

I'll close this for now and re-open if I do run into it again and have more info (but hey, at least now I can debug!)

**Comment by deadpahn** [comment]
Semi related ...

As a noise artist ... it would be cool to be able to open non tradition files to get that hard distorted static. Back in the fast tracker 2 days if I needed some crazy distortion as a synth I would simply open a random .exe file as an audio file. Just a feature request I'd like to share.
