### ISSUE TITLE
Notes with any volume setting get muted

### ISSUE THREAD

**Issue by rednorka** [asiekierka/nitrotracker#123]
NitrousTracker 0.4.12 on Nintendo DSi ran via TWiLightMenu++

Simply play a note that has a volume set (even 7F) on the pattern. The note will not play at all.

**Comment by asiekierka** [comment]
oops

**Comment by asiekierka** [comment]
https://github.com/asiekierka/libntxm/commit/23809f5970f8138c9ee017f683fefd1633ba8b89
