### ISSUE TITLE
Proposed new name ...

### ISSUE THREAD

**Issue by deadpahn** [asiekierka/nitrotracker#14]
In honor of Triton teams flagship DOS tracker FASTTRACKER 2, I think Nitrotracker 2 would fit because like with fastracker 2 the cool kids can just say "NT2" heh. It sounds good and all the OGs will love it I feel lol.
https://www.youtube.com/watch?v=BLMUfBikxTY

**Comment by asiekierka** [comment]
Sorry, but as much as I like the nod, I don't want to position myself as an official NitroTracker successor. It is an unofficial fork and the broad naming/designation rights should remain with 0xtob, IMO.
