### ISSUE TITLE
Create new folders

### ISSUE THREAD

**Issue by deadpahn** [asiekierka/nitrotracker#15]
Hi, me again.

It would be cool to be able to have a feature to create new folders. Right now I'm preparing for a show and I need to take songs that I will remix into a new folder. Instead of taking my sd card out and doing all that on my PC it would only take a second to make a new folder from the menu.

**Comment by illettante** [comment]
There could be a bit of scope creep here. You can already avoid breaking out the laptop to do basic file management operations on the DS with [GM9i](https://www.gamebrew.org/wiki/GodMode9i) via [twilightmenu](https://github.com/DS-Homebrew/TWiLightMenu/releases). It'd be nice to be able to do everything 'in camera' without leaving the program but i don't know if there's enough value in effectively implementing a fully-featured file manager within Nitro. Sorry if i'm [teaching you to suck eggs](https://en.wikipedia.org/wiki/Teaching_grandmother_to_suck_eggs#:~:text=Teaching%20(your)%20grandmother%20to%20suck,so%20than%20the%20first%20person) by the way, let me know and i'll pull my head in.

**Comment by deadpahn** [comment]
Its funny you mention that, somebody bought my discog the other day and put a similar message in there. All these ideas that Im giving are battle tested. I rely on NT for my shows and music. I've played sold out theaters using nitrotracker. Its my gimmick. Ive been tracking since 1996, am on the Blipfest 2007 DVD and have been following that culture/community for over 20 years.

I understand if you dont wanna hear it, thought I would give my input cause I thought you were taking the reins of NT development. Are you changes going to be merged with the NT master? I thought it was abandoned.

Fasttracker 2 has a new folder option (make dir)
![image](https://user-images.githubusercontent.com/1032331/222285674-1351bf31-f12a-4efa-845c-4af5ec1b3b85.png)

I'd consider myself an NT power user, but I get that my suggestions might be over bearing so I'll duck out.

Don't worry about the suck eggs thing, I've been working for gigantic software companies for decades I understand feature creep etc.

Thanks for the improvements you made thus far :)

**Comment by illettante** [comment]
IT WAS ME! Good choons, them.
Also i'm not the dev, that's @asiekierka, just an NT tragic sticking my opinion in, it's a workaround you can implement now (maybe not in time for this show but maybe in time for the next one) while/if dev considers the issue. 
Let it be so noted I'm basking in your thanks regardless of having made no improvements whatsoever ;P

**Comment by asiekierka** [comment]
This feature doesn't seem too difficult to add, but COVID is currently kicking my body and so it will have to wait some time... I apologize.

I also don't consider it to be scope creep - switching programs just to create a folder can be rather interrupting to the creative flow.

**Comment by illettante** [comment]
ah that sucks, get well soon. Ok, i see your point about breaking creative flow. maybe i'm not a good judge of that; my main creative tool right now is piggytracker on a 10+ year old dingoo so constant rebooting has become *part* of my creative 'flow' (if you could call it that!)

**Comment by asiekierka** [comment]
Added for the next release.

![](https://img.asie.pl/Eu79.png)

**Comment by deadpahn** [comment]
😲 AWESOME

**Comment by deadpahn** [comment]
Works great in 0.4.4!
