### ISSUE TITLE
Nice to see Nitrotracker is back in development

### ISSUE THREAD

**Issue by deadpahn** [asiekierka/nitrotracker#2]
Long story short, NitroTracker has replaced my laptop/computer for live performances. I've used it to to perform in front of sold out theaters, seedy goth bars, and at Blip Festival for the last decade. I've battle tested NitroTracker in the wild and thought I'd give my two cents in hopes of seeing the features I would love to see. 

In order of "this would be awesome to have":
LOCK PATTERN > JUMP TO PATTERN
So when I'm playing my songs live, sometimes I want to jump to other parts of the song that are not in the order of the .XM. Usually, I tap the track at the very moment the last pattern is about to end. This sort of works but I've messed it up a few times haha. A simple "LOCK" button (like in the KORG DS-10 pattern mode" would be awesome.

A simple track Timer/Clock
It would be nice to know how much time has passed since the track has started playing.

A simple "Draw waveform" feature
Would be nice. Right now I just make a noise in the microphone and try to go from there. But being able to make a simple saw or sine wave (or draw my own entirely) would be very neat.

"Oops not enough memory"
I've learned to use this as down time to talk to the crowd, but if there was some way to clear the memory or something better so that I can load the song? Usually I just restart the thing (when the DS ding hits over the load speakers it always gets a laugh from people so it's not so bad). 

Delete songs/Samples from card
Makes it easier for me to organize my files before a show if I'm on a plane or bus to the destination. Sure, use a laptop and an SD card adapter, but it would be desired to do this from inside NitroTracker. Not a big priority though.

Nibbles (like in FT2)
Just joking (but it would be cool, sometimes it's boring letting your songs play out. It would be nice to have something to do so it looks like im working haha)

Because of the cost and availability of the Old Nintendo DS, I really believe this will be a huge part of the live electronic music scene in the future. I hope that going forward features will remain compatible to some degree on the original DS. If I'm drunk as a skunk jumping into the crowd during a live show, I don't have to worry because I know I can replace the DS for $40. There is so much upside and value that NitroTracker brings to me as a live electronic artist that I just want to put my 2 cents here since it seems to be back in development. I'm fine with the 2 meg limits, it really forces me to be more creative. I've written a sox script to convert my samples to mono, 32k and the sound is so crunchy and Amiga like that I absolutely love it.

**Comment by asiekierka** [comment]
Hello! Thank you for the kind words - I appreciate them a lot. Sorry for not responding earlier - I have my hands in a lot of projects, and the NitroTracker fork didn't really have a high priority due to low response on release. Maybe I posted about it in the wrong places?

Your suggestions are very good, but please open them as separate issues next time - it makes it easier both for them to be tracked (an issue can be closed once it's resolved) and for potential outside contributors to not feel intimidated and jump straight in. I can't promise an ETA for resolving them, though - but I also can't say if someone else won't come along to have a look...
