### ISSUE TITLE
Can't "save as" files BUG

### ISSUE THREAD

**Issue by deadpahn** [asiekierka/nitrotracker#20]
Can't seem to "Save As" files. File names also have question marks as seen in the video. If I move to the parent folder I am able to save the new file.
https://user-images.githubusercontent.com/1032331/227415293-73a261bf-5adc-431c-aebb-9b23ac63c132.mp4

**Comment by asiekierka** [comment]
This *may* be fixed in 0.4.3? I'm not sure; feedback welcome!

**Comment by asiekierka** [comment]
Or 0.4.4, for that matter. That fixes a few more things.

**Comment by deadpahn** [comment]
So far looks good! I'll report if I run into issues again on that one.
