### ISSUE TITLE
Sample selection glitch and zoom issues on large files BUG

### ISSUE THREAD

**Issue by deadpahn** [asiekierka/nitrotracker#21]
Sample selection screen has glitching behavior see video below.
https://user-images.githubusercontent.com/1032331/227416087-a9a35325-b18b-4aaf-bb08-9b6a6e17239e.mp4

**Comment by asiekierka** [comment]
Do you mean these blinking triangles? That's a performance issue and not something that can be easily fixed with the current codebase (no UI double-buffering).

**Comment by deadpahn** [comment]
> Do you mean these blinking triangles? That's a performance issue and not something that can be easily fixed with the current codebase (no UI double-buffering).

It's the lack of highlighting on big files and also the Zoom doesn't work for big files sometimes. The triangles I thought were related to the highlight issue.

**Comment by asiekierka** [comment]
I've tried to reproduce it, but I'm not sure if I can come up with a sample necessary to do so. Could you please provide a copy of one?

**Comment by deadpahn** [comment]
I think the "glitch" I was perceiving was from the color of the highlight being so close to the color of the waveform. 
This will produce the same effect. Since the sample volume is so high, it looks like nothing is being highlighted when in fact it is (the color is too similar to the waveform).

[long_sample.wav.tar.gz](https://github.com/asiekierka/nitrotracker/files/11180852/long_sample.wav.tar.gz) (can't attach .wav files to this report)

For the "zoom" part it's kind of tricky to reproducing, and in trying to do so, I realized it can be worked around by spamming the zoom in and out for a couple of seconds.

**Comment by asiekierka** [comment]
Regarding the highlight issue, how's this?:

![](https://img.asie.pl/QPsV.png)

**Comment by deadpahn** [comment]
Looks GREAT!

**Comment by asiekierka** [comment]
The highlight color has been fixed some time ago, and some selection glitches will be fixed in the next release. I think that's it for this issue.

**Comment by deadpahn** [comment]
awesome!
