### ISSUE TITLE
New Samples are only "clicking" sounds in file browser BUG

### ISSUE THREAD

**Issue by deadpahn** [asiekierka/nitrotracker#23]
If I try to rip some samples from a file, they appear as "clicking" noises in the file preview window. If I load them they are usually fine. See video for how to reproduce the bug.
https://user-images.githubusercontent.com/1032331/227417659-bddc74e4-e833-4715-b008-cd01e6432861.mp4

**Comment by asiekierka** [comment]
https://github.com/asiekierka/libntxm/commit/fcf25bab95d01afe0a0f1dcf00cd5f396c967f3b

The bug seemed to be related to very short samples. Should be fixed in the next release.

**Comment by deadpahn** [comment]
Yup! Looks to be working now
