### ISSUE TITLE
Mono Toggle SUGGESTION

### ISSUE THREAD

**Issue by deadpahn** [asiekierka/nitrotracker#25]
If it isn't too difficult, I would love to have a MONO toggle for the main output. I mentioned how I hardpan elements of a song for live to maximize the potential of the DS using outboard gear before and I think this would actually be a simpler work around. Once I get a "live" version configured with the various hard pans, and unplug the DS from my studio set up, working on it in portable is a challenge since things are in a hard panned setting. 

I know this is totally MY fault but as I see people in the future using the DS ironically to make banger albums it is certain they will run into this issue.

Here is an example of a "LIVE" setup, (it had) a KAOSS PAD on one channel and the second channel is passing SYNC (made with the lovely new WAVEFORM DRAW function THANK YOU. Before it took a few tries using the microphone and various tricks to get a good one going out of the box) to a TD3. If I'm on my way to the show (usually on a bus, train, airplane, metro subway system etc) doing last minute changes it would be easier for me. My work around right now is to have the headphone be pulled out in a weird unreliable way to blend the sounds. Anyway, I thought I would document the idea.
https://user-images.githubusercontent.com/1032331/227424718-d72a95ca-2fbf-43da-b45e-c724748c8412.mp4

**Comment by asiekierka** [comment]
By "mono toggle", do you mean simply playing all samples on a center channel, with no panning?

**Comment by deadpahn** [comment]
> By "mono toggle", do you mean simply playing all samples on a center channel, with no panning?

Yes, without actually setting the samples panning property. The samples panning properties never get changed, it's more of an "effect" on the main output. So for people doing the "Drums on 1 channel and synths on the other" it's easier to work on songs on "the go". Also people syncing external hardware using sync clicks (there are a few people I've seen do this on youtube) will appreciate that as well when working on the train/bus/plane with headphones on (since for the technique to work properly things need to be hard panned).

Examples of people using the sync feature:
https://www.youtube.com/watch?v=37KeYRoZRN8

So some machine use a "click" to know what tempo/npm they should be going at. If the "sync" channel has other sounds on it, it won't work. So the artist has to hard pan the click (to say, the left channel and plug that into their devices) while channel 2 (the right channel) has key song elements.

**Comment by asiekierka** [comment]
Makes sense, not just for this use-case but as an accessibility feature in general.

Added for the next release:

![](https://img.asie.pl/bakK.png)

**Comment by deadpahn** [comment]
sick

**Comment by deadpahn** [comment]
I don't think you realize what you've done. When word gets out this is a game changer. The DS sound limitations can be circumvented now. I was playing a show with the legendary LENNY DEE, and he said to me "oh man thats so cool you are playing off of the DS, the BASS IS A LITTLE LOW tho". People can pump up the channel on a mixer now and apply whatever the want to mix finally in a now. My crusty work around was limited but now this makes it easier for people to get a good clean channel out of the DS mix. THANK YOU!

**Comment by asiekierka** [comment]
I appreciate and admire your enthusiasm! :-)
