### ISSUE TITLE
Visual artifact when "g", "q" letters, etc. are on last row of file selector

### ISSUE THREAD

**Issue by asiekierka** [asiekierka/nitrotracker#26]

**Comment by deadpahn** [comment]
Sorry fam, there is still a dot when scrolling through a big folder of songs:
![image](https://user-images.githubusercontent.com/1032331/230646036-982c833f-a6ff-4d76-b924-e7206be9d3b7.png)

**Comment by asiekierka** [comment]
I didn't close the issue :-)

I don't have much time allocated to work on the NitroTracker fork, so I wanted to release at least a few bugfixes.

**Comment by deadpahn** [comment]
I figured. Sorry if I'm bothering you with all the issues, thought it was
helpful.
