### ISSUE TITLE
Song name crashes NT [BUG]

### ISSUE THREAD

**Issue by deadpahn** [asiekierka/nitrotracker#28]
not joking, if you name a song "pingpoopoo" it will crash NT lol. I got different variations of this. When I had some notes in the songs the RAM bar went all green and I got the DOH error modal/popup. So I tried a few more times and if you just save a blank file with that name it RSOD (red screen of death :P) on me. It does the "?" thing to the file name too so maybe the other issue will resolve this one but I thought I'd file a bug report because the other naming issues didn't DOH or RSOD on me. Phone is in the kitchen, I can take a picture/video later if needed.

**Comment by asiekierka** [comment]
This *may* be fixed in 0.4.3? I'm not sure; feedback welcome!

**Comment by deadpahn** [comment]
The file name works now BUT as you can see in the video there is a bug with name files in their origin folders.

https://user-images.githubusercontent.com/1032331/230645892-bb5f1124-2bf8-425c-bbba-c862c702429c.mp4
