### ISSUE TITLE
Guru Meditation Error! data abort!

### ISSUE THREAD

**Issue by deadpahn** [asiekierka/nitrotracker#3]
![Screenshot_20200813-131419_Gallery](https://user-images.githubusercontent.com/1032331/90165749-262bdc00-dd67-11ea-8fb5-68a0b7112230.jpg)
Loaded some tracks that I created in the official release.

**Comment by asiekierka** [comment]
Do you have one of those tracks to share?

**Comment by a-a** [comment]
I get the same (including r0-r12,sp/lr/pc register values) just loading samples as well as trying to load tracks, in fact so far I haven't actually found anything that opens at all. This includes attempting to open the sample tracks included with the 0.41-beta release.
Loading a track seems to take a while, at which point the upper screen populates as expected, but then the red screen occurs, but given the crash can be replicated just by loading simple samples into an empty track my suspicion would be in how that's being handled.

Example of a sample that causes the crash:
```
$ base64 saw_256.wav 
UklGRiQBAABXQVZFZm10IBAAAAABAAEAqyAAAKsgAAABAAgAZGF0YQABAAB/fXt5d3VzcW9ta2ln
ZWNhX11bWVdVU1FPTUtJR0VDQT8+PDo4NjQyMC4sKigmJCIgHhwaGBYUEhAODAoIBgQC//37+ff1
8/Hv7evp5+Xj4d/d29nX1dPRz83LycfFw8G/vbu5t7Wzsa+tq6mnpaOhn52bmZeVk5GPjYuJh4WD
gX99e3l3dXNxb21raWdlY2FfXVtZV1VTUU9NS0lHRUNBPz48Ojg2NDIwLiwqKCYkIiAeHBoYFhQS
EA4MCggGBAL//fv59/Xz8e/t6+nn5ePh393b2dfV09HPzcvJx8XDwb+9u7m3tbOxr62rqaelo6Gf
nZuZl5WTkY+Ni4mHhYOB

```

**Comment by asiekierka** [comment]
What I'm worried about  is behaviour specific to a flashcart; are you running from a DSi/3DS SD card, or from a specific flashcart/loader?

**Comment by a-a** [comment]
Seems flashcart specific to me. Issue replicates on R4 SDHC, works fine on Supercard DSOne.

**Comment by asiekierka** [comment]
Please try launching https://github.com/devkitPro/nds-hb-menu first, then NitroTracker. Might be a firmware bug.

**Comment by AuCrossover** [comment]
I have the same problem but I'm using a 3DS SD card. I use the Twilight Menu to emulate the .nds rom. How do I fix this?

**Comment by asiekierka** [comment]
Not "emulate"; TwilightMenu++ runs in the DSi native mode that the 3DS provides.

Either way, please try launching from nds-hb-menu and let me know what happens. TwilightMenu++ is a pile of jank with piracy connotations, I'm not keen on supporting it.

**Comment by AuCrossover** [comment]
I tried using the latest nds-hb-menu, but it had the same result. Do you have another solution?

**Comment by AuCrossover** [comment]
I figured out how to fix it but i didn't use nds-hb-menu. I just had to update TwilightMenu++ and soon loading songs and/or samples won't have the error.

EDIT: Sliding the amplitude for a sample (if done fast) will cause it to have the same error.

**Comment by DeltaF1** [comment]
I'm also having this problem trying to load the demo xm files. Using the original v0.4 from the internet archive was working fine loading the same songs so it's definitely a regression.

Hardware: DSL + R4I-SDHC. I'm launching from the stock firmware but I will try using nds-hb-menu.

**Comment by Mr-Turnip** [comment]
> EDIT: Sliding the amplitude for a sample (if done fast) will cause it to have the same error.

Having the amplitude slider crash on me seems to be really conditional, I'm going to test it out a little more to see if I can find what causes it. (It always seems to crash from boot, but sometimes when I use another edit on a sample first it doesn't)

**Comment by spellboundtriangle** [comment]
I couldn't seem to get it working, I tried launching it from the latest TWLM++, the latest nds-hb-menu, the latest Unlaunch, the latest GodMode9i, and the latest nds-bootstrap-hb (it was worth a shot)... I also tried loading both the ROM and the song from the root, still didn't work.

However, running it through TWLM++ (in DS mode), then using the DS Classic Menu (a menu in TWLM++) to launch NitroTracker, it works fine, for some reason

**Comment by loquesangra** [comment]
@spellboundtriangle are you launching from a SDHC card? I'm using a 4GB one and also tried all the things you did, and did work ONLY with DS Classic Menu and having the ROM set to boot in DS mode, just like you. Haven't tested a smaller one, just thinking it might be related.

**Comment by spellboundtriangle** [comment]
> @spellboundtriangle are you launching from a SDHC card? I'm using a 4GB one and also tried all the things you did, and did work ONLY with DS Classic Menu and having the ROM set to boot in DS mode, just like you. Haven't tested a smaller one, just thinking it might be related.

Yeah, I am

**Comment by asiekierka** [comment]
As I am totally confused as to why this happens, I decided to recompile an 0.4.2-beta with newer libraries (and some fixes/improvements - 30KB more RAM for samples, I suppose) to see if that changes anything; as well as keep the .ELF files this time around, so I can make something out of the Guru Meditation Errors.

Hope that helps anything!

**Comment by deadpahn** [comment]
Tested it out on an R4 on a DSi and OG Launch DS, seems to be ok. I was loading my tracks while playing and it seemed to be alright now. I'll update the ticket if I find anything. THANK YOU for this, I use NitroTracker a lot.

 Made a clip to show you its working on an intensive track
https://www.youtube.com/shorts/IlcB2cpPeHY
