### ISSUE TITLE
Inverted scroll mode (0xtob/#26)

### ISSUE THREAD

**Issue by asiekierka** [asiekierka/nitrotracker#49]
>"inverted scroll mode" So i can freely move to a position on the pattern and the time/position-bar scrolls past. This way you can edit easily while looping the pattern .

**Comment by deadpahn** [comment]
"Scroll lock" is the term used in Renoise. This does actually make it easier to work on patterns in certain instances instead of start stopping all the time.

**Comment by asiekierka** [comment]
![](https://img.asie.pl/Sq0V.png)

Proposed design. "loop ptn" is moved to "loop" in the pattern tab, and replaced with a new option "scrl lock", which works as expected - detaches the cursor from playback, allowing editing while a pattern is playing.

Currently, I made it so that "scrl lock" implies "loop" (that is, it also locks the currently playing pattern) - I think that makes sense; do you?

**Comment by deadpahn** [comment]
The loop button makes so much sense there (muscle memory is going to be a pain to get rid of tho lol).

Ive clipped the renoise on/off icon for scroll lock if you need to be inspired for an icon (in case you need to save screen space later).
![renoise-scroll-lock](https://user-images.githubusercontent.com/1032331/230741174-464fb8d9-46f4-4332-b682-d5d4fbe749a7.png)

I can't believe this is happening btw lol

**Comment by asiekierka** [comment]
Remember that "scroll lock" also acts as an effective loop lock (it doesn't make sense to change patterns as part of song playback while you're editing).
