### ISSUE TITLE
Smaller record button (0xtob/#51)

### ISSUE THREAD

**Issue by asiekierka** [asiekierka/nitrotracker#70]
>The record button could be the standard red circle button, sing up much less screen space.

**Comment by deadpahn** [comment]
A RECORD toggle would be interesting as per our conversation in https://github.com/asiekierka/nitrotracker/issues/27#issuecomment-1500891970

**Comment by asiekierka** [comment]
The RECORD button is already a toggle; this issue just made it smaller.

**Comment by deadpahn** [comment]
Oh I meant pressing a button, unless that feature is there, I just spammed
all the buttons on the ds to get the record to turn on but I couldn't
figure it out.
