### ISSUE TITLE
Crash when adjusting sample amplitude

### ISSUE THREAD

**Issue by daniel-ferguson** [asiekierka/nitrotracker#78]
Hi! 

I'm seeing a reproducible crash (red screen,  "Guru Meditation Error!") when changing a sample's amplitude. Quickest way to see this for me has been:

1. Launch NitrousTracker
2. Record a sample
3. Go to modify its amplitude (scrolling up or down)

The crash happens while selecting a % value for the amplitude, before pressing "OK". The % at which it crashes doesn't seem to be consistent,. Following the steps above I seem to get crashes 100% of the time, but if I've been working on a project for a little while sometimes I can do amplitude changes with no crash.

**NitrousTracker:** 0.4.5 (reproduced in debug build as well as default, didn't try no-wifi)
**Flashcard:** Acekard 2i running hbmenu 0.7.1 (also tried Twilightmenu++ +& SD, same issue)
**Console**: DSi

---

Let me know if there's any other info I can provide to make this easier to track down.

P.S. this could be the same problem as something brought up later on in https://github.com/asiekierka/nitrotracker/issues/3

**Comment by asiekierka** [comment]
Is it the same issue as https://github.com/asiekierka/nitrotracker/issues/19 ?

**Comment by deadpahn** [comment]
I've been testing the new build and it's been happening in other areas when
you adjust parameters (wav drawing etc). I took some video clips I was
going to upload when I dump all my findings.

**Comment by daniel-ferguson** [comment]
Yes, looks like the same issue - sorry to open a dupe.

**Comment by asiekierka** [comment]
You've provided more information, so thank you! Please move further discussion to #19, however.
