### ISSUE TITLE
NitroTracker doesn't handle pattern break commands correctly

### ISSUE THREAD

**Issue by CCF100** [asiekierka/nitrotracker#79]
Example project: 
[mygg_josss_bonefish_-_turn_it_up.compat.zip](https://github.com/asiekierka/nitrotracker/files/11305972/mygg_josss_bonefish_-_turn_it_up.compat.zip)

**Comment by exelotl** [comment]
Lack of pattern delay and position jump commands appears to be what was causing this example to play incorrectly. These have been implemented in release [0.4.10](https://github.com/asiekierka/nitrotracker/releases/tag/0.4.10) and now the song plays decently!

(p.s. thank you for introducing me to this banger!)
