### ISSUE TITLE
File browser hangs on big directory 

### ISSUE THREAD

**Issue by deadpahn** [asiekierka/nitrotracker#83]
Directory with a lot of long samples (video is of a breakbeat directory) will hang for bit. If you are in sample browse mode and switch to song browse then BACK to sample browse it occurs too.

https://github.com/asiekierka/nitrotracker/assets/1032331/d236ec9b-30f8-4cb0-b040-c055639b4bb2

**Comment by asiekierka** [comment]
That's to be expected; SD card reads take some time. The next release should improve it a little.
