### ISSUE TITLE
sng and smp path not being saved

### ISSUE THREAD

**Issue by Alpdrucken** [asiekierka/nitrotracker#87]
In older versions of NT, the song and sample paths would be remembered by the app, while in newer versions the user needs to navigate back to the folders every time you open NT

**Comment by deadpahn** [comment]
You are right HOWEVER if you remove the folder (or rename etc) and tried to launch into old NT it would break. I had to delete the data folder to fix this which is a pain. I prefer the new way. If we go back tot he old way we would need some error handling or check to see if the folder exists or not. Before it was simply stored in a text file in the data folder I think. I dunno ... not a big deal breaker for me I like not having to worry about it. I rename files and folders all the time, I dont want to have to remember to delete the data folder everytime I do that.

**Comment by Alpdrucken** [comment]
truee i forgot that it even happened to me once haha good catch

**Comment by deadpahn** [comment]
> truee i forgot that it even happened to me once haha good catch

Also, if the last folder you were was huge it will hang for a bit and that's not something nice to start into lol. I do have a script that organizes big sample folders into smaller ones but sometimes Im lazy and wanna try something quick so I'll throw way too many samples into one folder (that's a me issue lol)
