### ISSUE TITLE
On-screen keyboard stays up when it should disappear

### ISSUE THREAD

**Issue by svkampen** [asiekierka/nitrotracker#89]
### Problem description
When opening, for instance, the song name editor, the on-screen keyboard stays up when I press "ok" or "cancel" - see attached screenshots. This also occurs in other cases when the OSK appears.

### Hardware
This is on a DS Lite, with an R4i Gold (r4ids.cn) card, with firmware version 1.50. I'd guess it is fairly hardware-specific -- otherwise somebody would have mentioned it by now, right? -- but perhaps there is some workaround possible?

#### 1. Start brand new session
![1_crop-1](https://github.com/asiekierka/nitrotracker/assets/979507/c7e547ee-a0e3-4ffb-b8ca-691df6017c77)

#### 2. Open song name editor
![2_crop-1](https://github.com/asiekierka/nitrotracker/assets/979507/01e4aed1-562b-42e2-8a39-58b7111baf6e)

#### 3. Close editor. After closing, on-screen keyboard persists.
![3_crop-1](https://github.com/asiekierka/nitrotracker/assets/979507/6cc7d076-795b-4a56-8d16-d857245cedba)

Cheers,
Sam

**Comment by asiekierka** [comment]
It's probably an update regression. I've noticed it too, but haven't had time to look into it deeper.

**Comment by asiekierka** [comment]
Could you please try with v0.4.7? It might have fixed itself...

**Comment by svkampen** [comment]
Oh, whoops, probably should have checked an earlier version! Both 0.4.5 and 0.4.7 work fine for me, yes!

After your first comment I tried looking into it myself but couldn't reproduce it when building 0.4.6 myself, so yeah, seems like an automatically resolved bug 😄.

Thanks,
Sam
