### ISSUE TITLE
"LIVE MIX" mode

### ISSUE THREAD

**Issue by deadpahn** [asiekierka/nitrotracker#9]
Hi,

First off, **_THANK YOU_** for improving NitroTracker.

I would like to see a LIVE MIX toggle button. What do I mean by this? Well, because of the output limitation of the DS audio, I've been experimenting with HARD PANNING my tracks so I can add a little spice on the mixer to post frequencies that are lacking. This is fun and all but hard panning a whole song and going back is a pain. It would be cool to be able to set each instrument (and sub instruments) as CHANNEL 1 or CHANNEL 2. So when you click "LIVE MODE" it toggles the hard pans of the instruments. So now you have 2 mono signals that can be put into channels of their own, allowing for better mixing. Why the toggle switch? Because working on a song with headphones, the hard pans aren't fun and setting them back and forth would be easier with this method.

The Nintendo DS has been my LIVE machine for a decade at least, and one thing I hear a lot from people is that the bass is low. I've had some sound techs do wonders on the default stereo output but its clear to me that this mono approach is the way to go.

Thanks!

**Comment by asiekierka** [comment]
Mmm, the problem is that NitroTracker uses an existing file format (`.xm`), so extending it would be a pain...

**Comment by deadpahn** [comment]
How about if you preface the instrument name with slug like 1 or 2? "CH1 - Drum" it maintains the xm spec but is sort of a markup for nitrotracker

**Comment by asiekierka** [comment]
That would work in theory, yes, but I'm not 100% keen on the idea.

**Comment by deadpahn** [comment]
Mono channel fixes this I think! THANKS! This is great
