### ISSUE TITLE
Recording screen is stuck

### ISSUE THREAD

**Issue by deadpahn** [asiekierka/nitrotracker#90]
Recording screen is stuck. See video

https://github.com/asiekierka/nitrotracker/assets/1032331/f8b675f4-52a6-4c0f-8f4d-9c81e95f2e76

**Comment by asiekierka** [comment]
Fixed in 0.4.8.

**Comment by deadpahn** [comment]
The screen still is stuck if you record for a while. Maybe auto close the window or have a count down timer? I tried holding it in counting to twenty to reproduce
