### ISSUE TITLE
Universal Updater ?

### ISSUE THREAD

**Issue by Golem642** [asiekierka/nitrotracker#92]
Hey do you mind if i add your app into the universal updater for 3DS ?
You'd still have full credit but i need permission from you to do it
Thanks !

**Comment by Davetheword** [comment]
That would be super cool!

**Comment by asiekierka** [comment]
Regarding Universal Updater: I do not generally grant *explicit* permissions for my software to be distributed by third-party mirrors; there are two reasons:

- First of all, doing so would imply a relationship of endorsement or approval, which I like to keep fairly close to my heart. 
- Second of all, for projects which are forks of other projects, I *cannot* legally grant any permissions which are not part of its terms - I do not own the copyright to much of the relevant code. At that point, why not just tell people to follow the license?

Therefore, if UU requires such endorsement or approval from me personally, it will not be granted. However, you are more than welcome to follow the same terms of the license everyone does and distribute the program while following its terms.

I apologize for the inconvenience. Feel free to refer them to this thread for clarification - but I'm sure they've heard the same story from me on my other projects.
