### ISSUE TITLE
Import sample loop points from file if present

### ISSUE THREAD

**Issue by rednorka** [asiekierka/nitrotracker#95]
Some WAV files store loop points for a file. It would be great to have it imported when present, or even store it when saving a sample from the program.

I'm not entirely sure about the technical side of this but it might be stored in a "smpl" chunk

**Comment by deadpahn** [comment]
Sort of related, sometimes playing with the loop points will guru crash NT. I've had it happen many times.

**Comment by asiekierka** [comment]
Can you provide an example of such a WAV file, for testing?

**Comment by rednorka** [comment]
Sure! I think I have a right example.

https://files.catbox.moe/sgmhfq.wav

This is a looped sample extracted from a DS game with VGMTrans. In this file the "smpl" chunk is located at the very end which has loop points stored in sample units. Some music-making software support this chunk.

**Comment by asiekierka** [comment]
https://github.com/asiekierka/libntxm/commit/2f48903953edcab764bb76dae2f5ba967aa9a3d8

Thank you!
