### ISSUE TITLE
Auto-stopping all sounds from previous pattern when new pattern starts. 

### ISSUE THREAD

**Issue by ultra3200** [asiekierka/nitrotracker#99]
New user here and first off i wanna say bigup for keeping this project alive..
Been using nitroustracker for a few days now and i can't figure out how to prevent a sound from overlapping  the following pattern, without cutting it exactly to lenght. This sucks for when you are trying to make a break where all previous samples suddenly need to come to a stop.
Now i usually cut my samples, which is a bit tedious, but i don't care.. exept for when it comes to long atmospheric samples or chromatically played bassline or pad samples. Chromatically played keys will also affect the length of that sample so when cutting the last key that was overlapping exactly to length, it will sometimes make the others too short. Same with basslines.
Would it be possible to give an "stopallsounds"command at the beginning (or end) of a pattern, so all previous samples stop resonating when the new patter starts? I hope this makes sense.. I definitely could use some help on the matter. Thanks in advance!
Keep it going.

**Comment by illettante** [comment]
Hi, hopefully this response is not so late as to be useless to you. 
If I understand your issue correctly, the 'note-off' command should be what you need. It's the "--" button in the bottom right corner, below "clr". If you want a pattern to start by silencing all the samples playing from the previous pattern, you'd put a 'note-off' command into the first step of every channel that didn't have a new note in it (which would stop the previous sample in the channel anyway).

**Comment by ultra3200** [comment]
Awesome, that was exactly what i was looking for.. Thanks for the reply mate, it's a great help!
